package com.kadamitas.warlockery.audit;

import static java.util.Map.entry;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.kadamitas.warlockery.registry.ContentCatalog;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

final class FtbItemsBlocksParityTest {
    private static final Set<String> VANILLA = Set.of("minecraft:crossbow", "minecraft:mutton");
    private static final Map<String, String> ITEMS = Map.ofEntries(
        entry("Alluring Skull", "alluringskull"),
        entry("Anointing Paste", "ingredient_annointing_paste"),
        entry("Apple of Sleeping", "ingredient_sleeping_apple"),
        entry("Armor Protection Poppet", "armor_mending_doll"),
        entry("Arthana", "ritual_knife"),
        entry("Attuned Stone", "ingredient_attuned_stone"),
        entry("Belladonna Flower", "ingredient_belladonna"),
        entry("Binky's Skull", "ingredient_fool_skull"),
        entry("Biome Beach", "biomenote"),
        entry("Boline", "boline"),
        entry("Bone Bolt", "ingredient_bolt_holy"),
        entry("Bone Needle", "ingredient_bone_needle"),
        entry("Book of Biomes", "ingredient_book_biomes"),
        entry("Book of Biomes (Extended Edition)", "bookbiomes2"),
        entry("Breath of the Goddess", "ingredient_breath_of_the_goddess"),
        entry("Brew Bag", "brewbag"),
        entry("Cane Sword", "canesword"),
        entry("Charm of Fanciful Thinking", "ingredient_charm_disrupted_dreams"),
        entry("Circle Talisman", "circletalisman"),
        entry("Clay Jar", "ingredient_clay_jar"),
        entry("Concentrated Bat Ball", "ingredient_bat_ball"),
        entry("Condensed Fear", "ingredient_condensed_fear"),
        entry("Cooked Porkchop?", "ingredient_odd_porkchop_cooked"),
        entry("Creative Bat/Wolf Token", "wolftoken"),
        entry("Creeper Heart", "ingredient_creeper_heart"),
        entry("Death Protection Poppet", "death_guard_doll"),
        entry("Demonic Blood", "ingredient_infernal_blood"),
        entry("Dense Web", "ingredient_web"),
        entry("Devils Tongue Charm", "silver_tongue_charm"),
        entry("Diamond Vapor", "ingredient_diamond_vapour"),
        entry("Drop of Luck", "ingredient_drop_of_luck"),
        entry("Duplication Grenade", "replication_charge"),
        entry("Earth Protection Poppet", "earth_guard_doll"),
        entry("Enchanted Broom", "ingredient_broom_enchanted"),
        entry("Ender Dew", "ingredient_ender_dew"),
        entry("Ent Twig", "ingredient_heartwood_splinter"),
        entry("Exhale of the Horned One", "ingredient_exhale_of_the_horned_one"),
        entry("Fanciful Thread", "ingredient_fanciful_thread"),
        entry("Fire Protection Poppet", "fire_guard_doll"),
        entry("Focused Will", "ingredient_focused_will"),
        entry("Foul Fume", "ingredient_foul_fume"),
        entry("Fume Filter", "ingredient_fume_filter"),
        entry("Garlic (item)", "garlic"),
        entry("Glass Goblet", "glassgoblet"),
        entry("Golden Chalk", "chalkheart"),
        entry("Graveyard Dust", "ingredient_graveyard_dust"),
        entry("Hand of Death", "deathshand"),
        entry("Heart of Gold", "ingredient_heartofgold"),
        entry("Hint of Rebirth", "ingredient_hint_of_rebirth"),
        entry("Hollow Tears Bucket", "buckethollowtears"),
        entry("Horn of the Hunt", "hornofthehunt"),
        entry("Hunger Protection Poppet", "hunger_guard_doll"),
        entry("Icy Needle", "ingredient_icy_needle"),
        entry("Impregnated Leather", "ingredient_impregnated_leather"),
        entry("Infernal Chalk", "chalkinfernal"),
        entry("Koboldite Dust", "ingredient_delvealloydust"),
        entry("Koboldite Ingot", "ingredient_delvealloyingot"),
        entry("Koboldite Nugget", "ingredient_delvealloynugget"),
        entry("Koboldite Pickaxe", "delvealloypickaxe"),
        entry("Lava Diviner", "divinerlava"),
        entry("Leonard's Urn", "archfiends_urn"),
        entry("Lilith's Blood", "ingredient_matriarchs_blood"),
        entry("Mandrake Root", "ingredient_mandrake_root"),
        entry("Mellifluous Hunger", "ingredient_mellifluous_hunger"),
        entry("Minedrake Bulb", "seedsdreamroot"),
        entry("Moon Charm", "mooncharm"),
        entry("Mutandis", "ingredient_verdant_catalyst"),
        entry("Mutandis Extremis", "ingredient_verdant_catalyst_prime"),
        entry("Mutating Sprig", "mutator"),
        entry("Mystic Branch", "mysticbranch"),
        entry("Necromantic Stone", "ingredient_necro_stone"),
        entry("Null Catalyst", "ingredient_nullcatalyst"),
        entry("Nullified Leather", "ingredient_nullifiedleather"),
        entry("Nullifying Bolt", "ingredient_bolt_anti_magic"),
        entry("Observations of an Immortal", "vampirebook"),
        entry("Odour of Purity", "ingredient_odour_of_purity"),
        entry("Oil of Vitriol", "ingredient_oil_of_vitriol"),
        entry("Otherwhere Chalk", "chalk_veil"),
        entry("Owlet's Wing", "ingredient_owlets_wing"),
        entry("Player Compass", "playercompass"),
        entry("Polynesia Charm", "beast_speech_charm"),
        entry("Poppet", "doll"),
        entry("Poppet Protection Poppet", "doll_guard"),
        entry("Poppet Shelf Compass", "shelfcompass"),
        entry("Purified Milk", "ingredient_purified_milk"),
        entry("Quartz Sphere", "ingredient_quartz_sphere"),
        entry("Raw Lambchop", "minecraft:mutton"),
        entry("Raw Meaty Stew", "stewraw"),
        entry("Raw Porkchop?", "ingredient_odd_porkchop_raw"),
        entry("Reek of Misfortune", "ingredient_reek_of_misfortune"),
        entry("Refined Evil", "ingredient_refined_evil"),
        entry("Ritual Chalk", "chalkritual"),
        entry("Rock", "ingredient_rock"),
        entry("Rowan Berries", "ingredient_berries_rowan"),
        entry("Rowan Door Key", "ingredient_door_key"),
        entry("Rowan Keyring", "ingredient_door_keyring"),
        entry("Silver Bolt", "ingredient_bolt_silver"),
        entry("Silver Deposits", "ingredient_silverdust"),
        entry("Soft Clay Jar", "ingredient_clay_jar_soft"),
        entry("Spear of the Huntsman", "thorn_spear"),
        entry("Spectral Dust", "ingredient_spectral_dust"),
        entry("Spectral Stone", "spectralstone"),
        entry("Spirit Bucket", "bucketspirit"),
        entry("Splitting Bolt", "ingredient_bolt_splitting"),
        entry("Staff of Duplication", "replication_staff"),
        entry("Subdued Spirit", "ingredient_subdued_spirit"),
        entry("Subdued Village Spirit", "ingredient_subdued_spirit_village"),
        entry("Sun Grenade", "sungrenade"),
        entry("Taglock Kit", "sympathetic_vial"),
        entry("Tear of the Goddess", "ingredient_tear_of_the_goddess"),
        entry("Toe of Frog", "ingredient_toe_of_frog"),
        entry("Tongue of Dog", "ingredient_dog_tongue"),
        entry("Tool Protection Poppet", "tool_mending_doll"),
        entry("Tormented Twine", "ingredient_tormented_twine"),
        entry("Torn Page", "ingredient_vbook_page"),
        entry("Vampiric Poppet", "blood_link_doll"),
        entry("Voodoo Poppet", "hexing_doll"),
        entry("Voodoo Protection Poppet", "hex_guard_doll"),
        entry("Warm Blood", "ingredient_warm_blood"),
        entry("Water Artichoke Globe", "ingredient_artichoke"),
        entry("Water Diviner", "divinerwater"),
        entry("Water Protection Poppet", "water_guard_doll"),
        entry("Waystone", "ingredient_waystone"),
        entry("Whiff of Magic", "ingredient_whiff_of_magic"),
        entry("Witch Hunter Pistol Crossbow", "minecraft:crossbow"),
        entry("Witchcraft: Brews & Infusions", "ingredient_book_infusions"),
        entry("Witchcraft: Circle Magic", "ingredient_book_circle_magic"),
        entry("Witchcraft: Collecting Fumes", "ingredient_book_oven"),
        entry("Witchcraft: Conjuration & Fetishes", "ingredient_book_burning"),
        entry("Witchcraft: Distilling", "ingredient_book_distilling"),
        entry("Witchcraft: Herbology", "ingredient_book_herbology"),
        entry("Witchcraft: Symbology", "ingredient_book_wands"),
        entry("Witches Hand", "arcane_focus"),
        entry("Witches' Brews", "cauldronbook"),
        entry("Wolfsbane (item)", "ingredient_wolfsbane"),
        entry("Wood Ash", "ingredient_ash_wood"),
        entry("Wooden Bolt", "ingredient_bolt_stake"),
        entry("Wool of Bat", "ingredient_bat_wool"),
        entry("Wormy Apple", "ingredient_apple_wormy"),
        entry("Woven Cruor", "ingredient_woven_cruor")
    );

    private static final Map<String, String> BLOCKS = Map.ofEntries(
        entry("Alder Leaves", "alder_leaves"),
        entry("Alder Planks", "alder_planks"),
        entry("Alder Wood", "alder_log"),
        entry("Alder Wood Door", "alderwooddoor"),
        entry("Beartrap", "beartrap"),
        entry("Blood Crucible", "bloodcrucible"),
        entry("Blood-stained Wool", "bloodedwool"),
        entry("Bloodied Wicker Bundle", "bloodedwool"),
        entry("Brazier", "brazier"),
        entry("Candelabra", "candelabra"),
        entry("Chalice", "chalice"),
        entry("Chalice (Filled)", "chalice"),
        entry("Coffin", "coffinblock"),
        entry("Crystal Ball", "crystalball"),
        entry("Disease", "disease"),
        entry("Dream Weaver of Fasting", "dreamcatcher"),
        entry("Dream Weaver of Fleet Foot", "dreamcatcher"),
        entry("Dream Weaver of Intensity", "dreamcatcher"),
        entry("Dream Weaver of Iron Arm", "dreamcatcher"),
        entry("Dream Weaver of Nightmares", "dreamcatcher"),
        entry("Dream Weavers", "dreamcatcher"),
        entry("Filtered Fume Funnel", "filteredfumefunnel"),
        entry("Fume Funnel", "fumefunnel"),
        entry("Garlic Garland", "garlicgarland"),
        entry("Hawthorn Leaves", "hawthorn_leaves"),
        entry("Hawthorn Planks", "hawthorn_planks"),
        entry("Hawthorn Wood", "hawthorn_log"),
        entry("Hellhound Head", "hellhound_head"),
        entry("Ice Door", "icedoor"),
        entry("Ice Fence", "icefence"),
        entry("Ice Gate", "icefencegate"),
        entry("Ice Pressure Plate", "icepressureplate"),
        entry("Ice Slab", "iceslab"),
        entry("Ice Stairs (Witchery)", "icestairs"),
        entry("Infinity Egg", "paradox_egg"),
        entry("Kettle", "kettle"),
        entry("Leech Chest", "leechchest"),
        entry("Mirror Surface", "mirrorwall"),
        entry("Pentacle", "pentacle"),
        entry("Perpetual Ice", "perpetualice"),
        entry("Poppet Shelf", "doll_shelf"),
        entry("Rowan Leaves", "rowan_leaves"),
        entry("Rowan Planks", "rowan_planks"),
        entry("Rowan Wood", "rowan_log"),
        entry("Rowan Wood Door", "rowanwooddoor"),
        entry("Shaded Glass", "shadedglass"),
        entry("Silver Vat", "silvervat"),
        entry("Snow Pressure Plate", "snowpressureplate"),
        entry("Snow Slab", "snowslab"),
        entry("Snow Stairs", "snowstairs"),
        entry("Spirit Portal (Witchery)", "spiritportal"),
        entry("Statue of Broken Curses", "broken_hexes_statue"),
        entry("Statue of Hobgoblin Patron", "statueofworship"),
        entry("Statue of Occluded Summons", "occluded_summons_statue"),
        entry("Statue of The Goddess", "statuegoddess"),
        entry("Stockade", "stockade"),
        entry("Sun Collector", "daylightcollector"),
        entry("Torment Stone", "abyssal_stone"),
        entry("Trent Effigy", "trent"),
        entry("Wicker Bundle", "wickerbundle"),
        entry("Witch's Cauldron", "cauldron"),
        entry("Witch's Ladder", "hex_ladder"),
        entry("Witches Oven", "alchemical_oven"),
        entry("Wolf Altar", "wolfaltar"),
        entry("Wolf Head", "wolfhead"),
        entry("Wolftrap", "wolftrap")
    );

    @Test
    void everyFtbItemPageHasARegisteredModernImplementation() {
        assertCoverage(ITEMS, 140);
    }

    @Test
    void everyFtbBlockPageHasARegisteredModernImplementation() {
        assertCoverage(BLOCKS, 66);
    }

    private static void assertCoverage(final Map<String, String> pages, final int expected) {
        final Set<String> registered = Stream.of(
                ContentCatalog.BLOCKS.stream().map(ContentCatalog::modernize),
                ContentCatalog.ITEMS.stream().map(ContentCatalog::modernize),
                ContentCatalog.INGREDIENTS.stream().map(ContentCatalog::ingredientId)
            )
            .flatMap(stream -> stream)
            .collect(java.util.stream.Collectors.toUnmodifiableSet());
        assertEquals(expected, pages.size());
        assertEquals(expected, pages.keySet().stream().distinct().count());
        pages.forEach((page, id) -> {
            assertTrue(!page.isBlank() && !id.isBlank());
            assertTrue(registered.contains(id) || VANILLA.contains(id), () -> page + " maps to missing " + id);
        });
    }
}
