package com.kadamitas.warlockery.entity;

import com.kadamitas.warlockery.registry.ModEntities;
import com.kadamitas.warlockery.item.SympatheticBinding;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.util.ProblemReporter;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntitySpawnReason;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.EntityTypes;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.monster.zombie.Zombie;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.TagValueInput;
import net.minecraft.world.level.storage.TagValueOutput;
import net.minecraft.world.phys.Vec3;

public final class BrambleColossusGameTests {
    private BrambleColossusGameTests() {}
    public static void brambleColossusPostSweepDisplaysThenThreshes(GameTestHelper h){Fixture f=new Fixture(h);var c=f.colossus();TreefydState.toggleWandering(c);var z=f.living(new BlockPos(9,1,7));f.clearSight(c,z);float hp=z.getHealth();var hitDuringDisplay=new boolean[]{false};h.onEachTick(()->{if(hitDuringDisplay[0]||c.colossusTransient().phase()!=BrambleColossusRules.Phase.DISPLAY||c.colossusCounters().displays==0)return;try{BrambleColossusRuntime.onAcceptedDamage(c,h.getLevel(),z,1.0F);hitDuringDisplay[0]=true;h.assertTrue(c.colossusTransient().phase()==BrambleColossusRules.Phase.THRESH,"accepted display damage advances directly to thresh");h.assertTrue(c.colossusTransient().pending()==null&&z.getUUID().equals(c.colossusTransient().subject()),"display damage never rewinds a pending mark");}catch(RuntimeException failure){f.close();throw failure;}});f.after(110,()->{h.assertTrue(hitDuringDisplay[0],"a real sweep reaches display before accepted damage");h.assertTrue(c.colossusCounters().sweeps>0,"a due capped sweep executes");h.assertTrue(c.colossusCounters().rawVisits<=6*c.colossusCounters().sweeps,"six raw visits per sweep");h.assertValueEqual(c.colossusCounters().displays,1,"exactly one display precedes thresh");h.assertTrue(c.colossusState().displayCooldownRemaining()>0,"display cooldown persists");h.assertTrue(z.getHealth()<=hp,"only thresh may harm");});}
    public static void brambleColossusAllowlistAndMakerAreNeverStruck(GameTestHelper h){Fixture f=new Fixture(h);var c=f.colossus();var maker=f.living(new BlockPos(9,1,7));var listed=f.living(new BlockPos(9,1,7));CreatureBehaviorState.bind(c,maker.getUUID());h.assertTrue(TreefydState.toggleAllowedResult(c,SympatheticBinding.from(listed))==TreefydState.ToggleResult.ADDED,"listed subject is stored through the production toggle");f.clearSight(c,maker);f.clearSight(c,listed);BrambleColossusRuntime.onAcceptedDamage(c,h.getLevel(),maker,1);BrambleColossusRuntime.onAcceptedDamage(c,h.getLevel(),listed,1);h.assertValueEqual(c.colossusState().nerve(),84,"both accepted hits affect nerve without granting attack legality");f.after(90,()->{h.assertTrue(c.colossusState().nerve()>=84,"ordinary recovery alone may raise nerve afterward");h.assertTrue(c.colossusTransient().subject()==null&&c.colossusTransient().pending()==null,"maker and listed subject are never bound");h.assertTrue(c.colossusCounters().thornEvents==0,"maker and listed subject are never thorned");h.assertTrue(c.colossusCounters().uuidResolves<=27,"each alarm resolves at most nine UUIDs");});}
    public static void brambleColossusCircuitAndStanceStayInsideThePost(GameTestHelper h){
        Fixture f=new Fixture(h);var c=f.colossus();BlockPos p=c.colossusState().post().orElseThrow();
        var witness=f.living(new BlockPos(11,1,7));float witnessHealth=witness.getHealth();
        h.assertTrue(TreefydState.toggleAllowedResult(c,SympatheticBinding.from(witness))==TreefydState.ToggleResult.ADDED,"quota witness cannot distract the circuit owner");
        var quotaMobs=new ArrayList<BrambleColossusEntity>();
        for(int i=0;i<5;i++){var auxiliary=f.colossus();f.clearSight(auxiliary,witness);BrambleColossusRuntime.onAcceptedDamage(auxiliary,h.getLevel(),witness,1);quotaMobs.add(auxiliary);}
        var quotaObserved=new boolean[]{false};
        h.onEachTick(()->{if(quotaObserved[0])return;int displays=quotaMobs.stream().mapToInt(m->m.colossusCounters().displays).sum();if(displays<5)return;
            h.assertTrue(quotaMobs.stream().mapToInt(m->m.colossusCounters().deferred).sum()>=1,"the fifth simultaneous display waits at the quota gate");
            h.assertValueEqual(quotaMobs.stream().mapToInt(m->m.colossusCounters().sounds).sum(),5,"every display emits its mandatory sound exactly once");
            h.assertValueEqual(quotaMobs.stream().mapToInt(m->m.colossusCounters().particles).sum(),40,"every display emits its mandatory eight particles exactly once");
            h.assertTrue(quotaMobs.stream().allMatch(m->m.colossusTransient().phase()==BrambleColossusRules.Phase.DISPLAY&&m.colossusState().displayCooldownRemaining()>0),"quota denial defers in display and the retry arms cooldown once");
            h.assertValueEqual(witness.getHealth(),witnessHealth,"display retry causes no silent contact harm");
            quotaMobs.forEach(m->{TreefydState.toggleAllowedResult(m,SympatheticBinding.from(witness));BrambleColossusRuntime.cancel(m);});quotaObserved[0]=true;
        });
        h.assertTrue(!TreefydState.toggleWandering(c),"tool-equivalent toggle plants the colossus");
        h.runAfterDelay(80,()->{h.assertValueEqual(c.colossusCounters().paths,0,"planted stance owns movement cancellation");h.assertTrue(TreefydState.toggleWandering(c),"second toggle enables pacing");});
        f.after(300,()->{h.assertTrue(quotaObserved[0],"denied display retries on the next available quota tick");h.assertTrue(c.colossusState().post().orElseThrow().equals(p),"circuit retains post");h.assertTrue(c.colossusCounters().paths>0,"a real circuit route is attempted while pacing");h.assertTrue(c.position().distanceToSqr(Vec3.atCenterOf(p))<=196,"routine stays inside leash");h.assertTrue(c.colossusCounters().blockEdits==0&&c.colossusCounters().entityCreations==0,"zero family block edits and creations");h.assertTrue(!c.isNoAi(),"stance never uses noAi");});
    }
    public static void brambleColossusNerveFaltersAndRecoversDeterministically(GameTestHelper h){Fixture f=new Fixture(h);var c=f.colossus();c.setColossusState(c.colossusState().withNerve(25));var probe=f.colossus(new BlockPos(2,1,2));var outside=f.living(new BlockPos(12,1,12));f.clearSight(probe,outside);f.after(70,()->{h.assertValueEqual(c.colossusState().nerve(),26,"one recovery per sixty loaded ticks");h.assertTrue(c.colossusTransient().subject()==null&&c.colossusTransient().pending()==null,"falter clears episode");h.assertTrue(c.colossusCounters().effects==0,"zero effects");h.assertTrue(probe.colossusCounters().sweeps>0,"the diagonal outsider is observed by a real capped AABB sweep");h.assertTrue(probe.colossusTransient().pending()==null&&probe.colossusTransient().subject()==null&&probe.colossusCounters().displays==0,"an AABB-corner subject outside the held cylinder never binds or proceeds");});}
    public static void brambleColossusHazardEscapeAndCancellationAreDeterministic(GameTestHelper h){Fixture f=new Fixture(h);var c=f.colossus();f.place(c.blockPosition(),Blocks.FIRE.defaultBlockState());c.setRemainingFireTicks(100);f.after(45,()->{h.assertTrue(c.colossusCounters().hazardSearches>0,"bounded safe search runs");h.assertTrue(c.colossusCounters().safeCandidates<=16*c.colossusCounters().hazardSearches,"sixteen candidates per search");h.assertTrue(c.colossusCounters().blockReads<=BrambleColossusRules.SAFE_SEARCH_READS*c.colossusCounters().hazardSearches+BrambleColossusRules.HAZARD_OBSERVATION_READS*3,"charged search and observations stay capped");h.assertTrue(c.colossusCounters().occupancyVisits<=BrambleColossusRules.SAFE_SEARCH_VISITS*c.colossusCounters().hazardSearches,"entity collision visits stay capped");h.assertTrue(c.colossusCounters().cancellations>0&&c.colossusTransient().pending()==null&&c.colossusTransient().subject()==null,"hazard tears down episode");h.assertTrue(c.position().distanceToSqr(Vec3.atCenterOf(c.colossusState().post().orElseThrow()))<=196,"escape remains inside leash");h.assertTrue(c.colossusCounters().blockEdits==0&&c.colossusCounters().effects==0,"zero family edits and effects");});}
    public static void brambleColossusSaveReloadAndZombieLifecycleAreReplaced(GameTestHelper h){Fixture f=new Fixture(h);var original=f.colossus();original.setColossusState(original.colossusState().postedAt(new BlockPos(Integer.MAX_VALUE,Integer.MAX_VALUE,Integer.MIN_VALUE)).withNerve(42).withLeg(3).withDisplayCooldown(511).withCircuitCooldown(2111));original.setCanPickUpLoot(true);original.setItemSlot(EquipmentSlot.MAINHAND,new net.minecraft.world.item.ItemStack(Items.DIAMOND));original.setHealth(.5F);CompoundTag expected=original.colossusState().write();TagValueOutput out=TagValueOutput.createWithContext(ProblemReporter.DISCARDING,h.getLevel().registryAccess());original.saveWithoutId(out);CompoundTag saved=out.buildResult().copy();original.discard();var loaded=(BrambleColossusEntity)ModEntities.ALL.get("bramble_colossus").get().create(h.getLevel(),EntitySpawnReason.LOAD);h.assertTrue(loaded!=null,"dedicated factory reloads");loaded.load(TagValueInput.create(ProblemReporter.DISCARDING,h.getLevel().registryAccess(),saved));h.assertTrue(!loaded.canPickUpLoot(),"pickup normalizes during load");h.assertTrue(loaded.getItemBySlot(EquipmentSlot.MAINHAND).isEmpty(),"equipment normalizes during load");h.assertTrue(loaded.getHealth()>=1,"health normalizes during load");f.track(loaded);h.getLevel().addFreshEntity(loaded);f.after(1,()->{h.assertTrue(!Zombie.class.isAssignableFrom(loaded.getClass()),"not Zombie");h.assertTrue(h.getLevel().getWorldBorder().isWithinBounds(loaded.colossusState().post().orElseThrow())&&!h.getLevel().isOutsideBuildHeight(loaded.colossusState().post().orElseThrow()),"loaded post reconciles to playable bounds");h.assertTrue(loaded.colossusTransient().phase()==BrambleColossusRules.Phase.KEEPING,"phase normalizes");h.assertValueEqual(loaded.colossusState().nerve(),42,"nerve survives");h.assertValueEqual(loaded.colossusState().leg(),3,"leg survives");h.assertTrue(expected.contains("SchemaVersion")&&!expected.contains("Version"),"exact schema key");h.assertTrue(h.getLevel().getEntity(loaded.getUUID())==loaded,"reload UUID resolves exactly to the replacement");h.assertTrue(loaded.colossusCounters().displays==0&&loaded.colossusCounters().meleeAttempts==0&&loaded.colossusCounters().thornEvents==0,"no phase or combat counters replay");});}
    private static final class Fixture implements AutoCloseable{
        final GameTestHelper h;final List<Entity> entities=new ArrayList<>();final List<BlockPos> shell=new ArrayList<>(),placed=new ArrayList<>();final java.util.Map<BlockPos,net.minecraft.world.level.block.state.BlockState> restored=new java.util.LinkedHashMap<>();Fixture(GameTestHelper h){this.h=h;shell();}
        BrambleColossusEntity colossus(){return colossus(new BlockPos(7,1,7));}
        BrambleColossusEntity colossus(BlockPos relative){var e=ModEntities.ALL.get("bramble_colossus").get().create(h.getLevel(),EntitySpawnReason.EVENT);h.assertTrue(e instanceof BrambleColossusEntity,"dedicated factory");var c=(BrambleColossusEntity)e;BlockPos p=h.absolutePos(relative);c.snapTo(p.getX()+.5,p.getY(),p.getZ()+.5);c.recordPost(p);c.setPersistenceRequired();track(c);h.assertTrue(h.getLevel().addFreshEntity(c),"fixture colossus enters the live level");return c;}
        LivingEntity living(BlockPos r){var e=EntityTypes.SHEEP.create(h.getLevel(),EntitySpawnReason.EVENT);h.assertTrue(e!=null,"fixture subject factory");BlockPos p=h.absolutePos(r);e.snapTo(p.getX()+.5,p.getY(),p.getZ()+.5);e.getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(0);track(e);h.assertTrue(h.getLevel().addFreshEntity(e),"fixture subject enters the live level");return e;}
        void clearSight(LivingEntity a,LivingEntity b){BlockPos from=BlockPos.containing(a.getEyePosition()),to=BlockPos.containing(b.getEyePosition());for(BlockPos p:BlockPos.betweenClosed(Math.min(from.getX(),to.getX()),Math.min(from.getY(),to.getY()),Math.min(from.getZ(),to.getZ()),Math.max(from.getX(),to.getX()),Math.max(from.getY(),to.getY()),Math.max(from.getZ(),to.getZ()))){var old=h.getLevel().getBlockState(p);if(!old.isAir()){restored.putIfAbsent(p.immutable(),old);h.getLevel().setBlock(p,Blocks.AIR.defaultBlockState(),3);}}}
        void track(Entity e){entities.add(e);}void place(BlockPos p,net.minecraft.world.level.block.state.BlockState s){if(h.getLevel().getBlockState(p).isAir()){h.getLevel().setBlock(p,s,3);placed.add(p);}}void after(long d,Runnable a){h.runAfterDelay(d,()->{try{a.run();h.succeed();}finally{close();}});}
        void shell(){BlockPos c=h.absolutePos(new BlockPos(7,1,7));int radius=6,wall=radius,height=6;for(int x=-wall;x<=wall;x++)for(int z=-wall;z<=wall;z++)for(int y=-1;y<=height;y++){boolean perimeter=Math.abs(x)==wall||Math.abs(z)==wall||y==height||y==-1;if(!perimeter)continue;BlockPos p=c.offset(x,y,z);if(h.getLevel().getBlockState(p).isAir()){h.getLevel().setBlock(p,Blocks.BARRIER.defaultBlockState(),3);shell.add(p);}}}
        public void close(){entities.forEach(Entity::discard);restored.forEach((p,s)->h.getLevel().setBlock(p,s,3));placed.forEach(p->h.getLevel().setBlock(p,Blocks.AIR.defaultBlockState(),3));shell.forEach(p->h.getLevel().setBlock(p,Blocks.AIR.defaultBlockState(),3));}
    }
}
