package com.kadamitas.warlockery.entity;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import net.minecraft.core.BlockPos;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.AbortableIterationConsumer;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.entity.EntityTypeTest;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;

public final class DreamrootRuntime {
    public enum CancellationReason { REMOVAL, TELEPORT, DIMENSION_CHANGE, DEATH, DISCARD, TRADE, SLEEP, RAID, PANIC, BREEDING, HAZARD, SUBJECT_INVALID, TOKEN_DENIED, UNLOAD }
    private static final List<BlockPos> SAFE_OFFSETS=List.of(new BlockPos(2,0,0),new BlockPos(-2,0,0),new BlockPos(0,0,2),new BlockPos(0,0,-2),new BlockPos(2,0,2),new BlockPos(2,0,-2),new BlockPos(-2,0,2),new BlockPos(-2,0,-2),new BlockPos(3,0,0),new BlockPos(-3,0,0),new BlockPos(0,0,3),new BlockPos(0,0,-3),new BlockPos(3,0,3),new BlockPos(3,0,-3),new BlockPos(-3,0,3),new BlockPos(-3,0,-3));
    private DreamrootRuntime(){}
    public static final class TransientState {DreamrootRules.Phase phase=DreamrootRules.Phase.ROOTED;int phaseTicks,hintTicks,combatTicks,meleeDelay,unseenTicks,routeDelay,routeFailures,routeBackoff,attackerTick;UUID subject,hint,attacker;ResourceKey<Level> subjectDimension,attackerDimension,lastDimension;BlockPos anchor,escapeDestination;boolean escapeAbandon,escapeRouteActive;Vec3 lastPosition;public DreamrootRules.Phase phase(){return phase;}public void resetForLoad(){phase=DreamrootRules.Phase.ROOTED;phaseTicks=hintTicks=combatTicks=meleeDelay=unseenTicks=routeDelay=routeFailures=routeBackoff=attackerTick=0;subject=hint=attacker=null;subjectDimension=attackerDimension=lastDimension=null;anchor=escapeDestination=null;escapeAbandon=escapeRouteActive=false;lastPosition=null;}}
    public static final class Counters {public int aiTicks,cheapDecisions,rootedTicks,episodeStarts,episodeCancelsByReason;public int thresholdChecks,rawVisits,sightRays,stirStarts,stirCancels,dreamCommits,dreams,dreamBlockedUprooted,darknessApplications;public int sustainTicks,sustainHeals,sustainBlockReads,attackerAttributions,attackerRejectionsByReason,attackerExpiries,meleeAttempts,meleeAccepted;public int pathRequests,pathsAccepted,pathFailures,pathBackoffs,navigationOverwrites,reanchors;public int hazardObservationReads,safeCandidates,safeReads,safeEntityVisits,hazardRoutes,hazardEscapeSuccesses,unrootEvents,rerootEvents;public int bulbWakeEvaluations,bulbCreations,bulbDeferred,bulbOwnerHints,nearestPlayerQueries;public int tokensGranted,tokensDeferred,feedbackEmitted,feedbackSuppressed,sounds,particles;public int genericBehaviorDispatches,genericTacticalDispatches,genericAmbientDispatches,genericHazardDispatches;public int slownessApplications,poisonApplications,weaknessApplications,thornsDamageEvents,explosions,reinforcements;public int villagerConversions,drownedConversions,turtleEggBreaks,doorBreaks,babyStates,equipmentStates;public int blockEdits,chunkLoadRequests,entityCreationsOutsideBulbPath,stateKeys,stateBytes,stateMismatches,transientReplays;public int cancellations;public long serverTickNs;}

    public static void tick(DreamrootEntity mob,ServerLevel level){DreamrootState state=mob.dreamrootState();TransientState s=mob.dreamrootTransient();Counters c=mob.dreamrootCounters();c.aiTicks++;if(s.lastDimension!=null&&s.lastDimension!=level.dimension()){cancelEpisode(mob,CancellationReason.DIMENSION_CHANGE);s.anchor=mob.blockPosition();}else if(s.lastPosition!=null&&(!LivingRootsRules.rooted(s.phase)||s.subject!=null||s.attacker!=null)&&s.lastPosition.distanceToSqr(mob.position())>64.0D){cancelEpisode(mob,CancellationReason.TELEPORT);s.anchor=mob.blockPosition();}s.lastDimension=level.dimension();s.lastPosition=mob.position();if(s.anchor==null)s.anchor=mob.blockPosition();state=new DreamrootState(1,LivingRootsRules.decrementLoaded(state.dreamCooldownRemaining()),(state.sustainRemainder()+1)%DreamrootRules.SUSTAIN_CADENCE_TICKS,LivingRootsRules.decrementLoaded(state.episodeCooldownRemaining()));if(s.hintTicks>0)s.hintTicks--;else s.hint=null;if(s.routeDelay>0)s.routeDelay--;if(s.routeBackoff>0)s.routeBackoff--;
        CancellationReason actorCancellation=actorCancellationReason(subject(level,s.subject,s.subjectDimension));
        if(actorCancellation==null)actorCancellation=actorCancellationReason(subject(level,s.attacker,s.attackerDimension));
        if(actorCancellation!=null){cancelEpisode(mob,actorCancellation);s.phase=DreamrootRules.Phase.ROOTED;s.anchor=mob.blockPosition();}
        final boolean hazard=hazardActive(mob,level);if(hazard&&s.phase!=DreamrootRules.Phase.ESCAPE){cancelEpisode(mob,CancellationReason.HAZARD);s.phase=DreamrootRules.Phase.ESCAPE;c.unrootEvents++;}if(s.phase==DreamrootRules.Phase.ESCAPE){escape(mob,level,hazard);mob.setDreamrootState(state);return;}
        if(actorCancellation!=null){mob.setDreamrootState(state);return;}
        tickCombat(mob,level);if(state.sustainRemainder()==0){c.sustainBlockReads++;if(livingGround(mob)){mob.heal(DreamrootRules.sustainAmount(CreatureBehaviorState.empowerment(mob)));c.sustainTicks++;c.sustainHeals++;}}s.phaseTicks++;
        if(s.phase==DreamrootRules.Phase.ROOTED){c.rootedTicks++;stop(mob);if(state.dreamCooldownRemaining()==0&&LivingRootsRules.staggeredDue(mob.tickCount,mob.getId(),DreamrootRules.THRESHOLD_CADENCE_TICKS))observe(mob,level);}
        else if(s.phase==DreamrootRules.Phase.STIR){LivingEntity target=subject(level,s.subject,s.subjectDimension);if(target==null||!eligible(mob,target)||mob.distanceToSqr(target)>DreamrootRules.OUTER_RADIUS*DreamrootRules.OUTER_RADIUS){s.phase=DreamrootRules.Phase.ROOTED;s.subject=null;s.subjectDimension=null;c.stirCancels++;}else if((mob.tickCount%10)==0){var q=LivingRootsRules.quota(level);if(q.sight()){c.sightRays++;if(mob.hasLineOfSight(target))s.unseenTicks=0;else s.unseenTicks+=10;}if(s.unseenTicks>=20){s.phase=DreamrootRules.Phase.ROOTED;s.subject=null;s.subjectDimension=null;c.stirCancels++;}}if(s.phase==DreamrootRules.Phase.STIR&&s.phaseTicks>=DreamrootRules.ONSET_TICKS&&mob.distanceToSqr(target)<=DreamrootRules.INNER_RADIUS*DreamrootRules.INNER_RADIUS){var q=LivingRootsRules.quota(level);if(q.sight()){c.sightRays++;if(mob.hasLineOfSight(target))s.phase=DreamrootRules.Phase.THRESHOLD;}}}
        if(s.phase==DreamrootRules.Phase.THRESHOLD){LivingEntity target=subject(level,s.subject,s.subjectDimension);if(target==null){s.phase=DreamrootRules.Phase.ROOTED;s.subjectDimension=null;}else if(!livingGround(mob)){c.dreamBlockedUprooted++;s.phase=DreamrootRules.Phase.SUBSIDE;s.phaseTicks=0;state=new DreamrootState(1,DreamrootRules.DREAM_COOLDOWN_TICKS,state.sustainRemainder(),state.episodeCooldownRemaining());}else{boolean granted=LivingRootsRules.quota(level).dream();s.phase=DreamrootRules.afterDreamToken(granted);if(!granted)c.tokensDeferred++;else{c.tokensGranted++;c.dreamCommits++;target.addEffect(new MobEffectInstance(MobEffects.DARKNESS,DreamrootRules.dreamDuration(CreatureBehaviorState.empowerment(mob)),0));feedback(mob,level);c.dreams++;c.darknessApplications++;s.subject=null;s.subjectDimension=null;s.phase=DreamrootRules.Phase.SUBSIDE;s.phaseTicks=0;state=new DreamrootState(1,DreamrootRules.DREAM_COOLDOWN_TICKS,state.sustainRemainder(),state.episodeCooldownRemaining());}}}else if(s.phase==DreamrootRules.Phase.SUBSIDE&&s.phaseTicks>=DreamrootRules.SUBSIDE_TICKS){s.phase=DreamrootRules.Phase.ROOTED;s.phaseTicks=0;s.subject=null;s.subjectDimension=null;}
        mob.setDreamrootState(state);
    }
    private static void observe(DreamrootEntity mob,ServerLevel level){Counters c=mob.dreamrootCounters();c.thresholdChecks++;var q=LivingRootsRules.quota(level);if(!q.expensive()){c.tokensDeferred++;return;}var list=new ArrayList<LivingEntity>();level.getEntities(EntityTypeTest.forClass(LivingEntity.class),mob.getBoundingBox().inflate(DreamrootRules.OUTER_RADIUS),e->true,list,DreamrootRules.RAW_CANDIDATE_CAP);if(!q.entities(list.size())){c.tokensDeferred++;return;}c.rawVisits+=list.size();final UUID hint=mob.dreamrootTransient().hint;list.stream().filter(e->eligible(mob,e)).sorted((left,right)->DreamrootRules.compareCandidate(mob.distanceToSqr(left),hint,left.getUUID(),mob.distanceToSqr(right),right.getUUID())).limit(DreamrootRules.SIGHT_CAP).filter(e->{if(!q.sight())return false;c.sightRays++;return mob.hasLineOfSight(e);}).findFirst().ifPresent(e->{TransientState s=mob.dreamrootTransient();s.subject=e.getUUID();s.subjectDimension=e.level().dimension();s.phase=DreamrootRules.Phase.STIR;s.phaseTicks=s.unseenTicks=0;c.stirStarts++;c.episodeStarts++;});}
    private static boolean eligible(DreamrootEntity mob,LivingEntity e){return e!=mob&&e.isAlive()&&!e.isRemoved()&&e.level()==mob.level()&&!(e instanceof MandrakeEntity)&&!(e instanceof DreamrootEntity)&&!e.hasEffect(MobEffects.DARKNESS)&&mob.canAttack(e)&&(!(e instanceof Player p)||!p.isCreative()&&!p.isSpectator()&&!p.isSleeping())&&(!(e instanceof net.minecraft.world.entity.npc.villager.AbstractVillager villager)||villager.getTradingPlayer()==null)&&!(e instanceof net.minecraft.world.entity.npc.villager.Villager villager&&(villager.getBrain().hasMemoryValue(net.minecraft.world.entity.ai.memory.MemoryModuleType.BREED_TARGET)||villager.getBrain().hasMemoryValue(net.minecraft.world.entity.ai.memory.MemoryModuleType.IS_PANICKING)||villager.getBrain().isActive(net.minecraft.world.entity.schedule.Activity.PANIC)))&&!(e instanceof net.minecraft.world.entity.raid.Raider raider&&raider.getCurrentRaid()!=null);}
    public static void hint(DreamrootEntity mob,UUID owner){TransientState s=mob.dreamrootTransient();s.hint=owner;s.hintTicks=200;mob.dreamrootCounters().bulbOwnerHints++;}
    public static void acceptedDamage(DreamrootEntity mob,LivingEntity attacker){acceptedDamageAt(mob,attacker,attacker.tickCount);}
    static void acceptedDamageAt(DreamrootEntity mob,LivingEntity attacker,int attackerTick){long age=(long)attacker.tickCount-attackerTick;if(!DreamrootRules.freshAttribution(age)){mob.dreamrootCounters().attackerExpiries++;return;}TransientState s=mob.dreamrootTransient();s.attacker=attacker.getUUID();s.attackerDimension=attacker.level().dimension();s.attackerTick=attackerTick;s.combatTicks=DreamrootRules.COMBAT_WINDOW_TICKS;s.meleeDelay=0;mob.dreamrootCounters().attackerAttributions++;}
    private static void tickCombat(DreamrootEntity mob,ServerLevel level){TransientState s=mob.dreamrootTransient();if(s.combatTicks<=0||s.attacker==null)return;s.combatTicks--;LivingEntity target=subject(level,s.attacker,s.attackerDimension);if(target==null||!eligible(mob,target)){s.attacker=null;s.attackerDimension=null;s.combatTicks=0;return;}if(!DreamrootRules.freshAttribution((long)target.tickCount-s.attackerTick)){mob.dreamrootCounters().attackerExpiries++;s.attacker=null;s.attackerDimension=null;s.combatTicks=0;return;}if(s.meleeDelay>0)s.meleeDelay--;if(mob.distanceToSqr(target)<=4&&s.meleeDelay==0){var q=LivingRootsRules.quota(level);if(q.sight()){mob.dreamrootCounters().sightRays++;if(mob.hasLineOfSight(target)&&q.melee()){mob.dreamrootCounters().meleeAttempts++;if(mob.doHurtTarget(level,target))mob.dreamrootCounters().meleeAccepted++;s.meleeDelay=DreamrootRules.MELEE_CADENCE_TICKS;}}}}
    private static boolean hazardActive(DreamrootEntity mob,ServerLevel level){if(mob.isOnFire()||mob.isInLava())return true;if(mob.hurtTime<=0||!LivingRootsRules.staggeredDue(mob.tickCount,mob.getId(),DreamrootRules.HAZARD_CADENCE_TICKS))return false;var q=LivingRootsRules.quota(level);var observation=LivingRootsRules.observeHazard(level,mob,DreamrootRules.HAZARD_FOOTPRINT_READ_CAP,DreamrootRuntime::unsafe);if(!q.reads(observation.actualReads()))return false;mob.dreamrootCounters().hazardObservationReads+=observation.actualReads();return observation.safe();}
    private static void escape(DreamrootEntity mob,ServerLevel level,boolean hazard){TransientState s=mob.dreamrootTransient();if(s.escapeDestination!=null){if(mob.distanceToSqr(s.escapeDestination.getX()+.5,s.escapeDestination.getY(),s.escapeDestination.getZ()+.5)<=2.25D){int[] visits={0},reads={0};if(safe(mob,level,s.escapeDestination,visits,reads)){s.escapeDestination=null;s.escapeRouteActive=false;s.routeFailures=s.routeBackoff=0;s.escapeAbandon=false;s.phase=DreamrootRules.Phase.ROOTED;s.anchor=mob.blockPosition();mob.dreamrootCounters().hazardEscapeSuccesses++;mob.dreamrootCounters().rerootEvents++;mob.dreamrootCounters().reanchors++;stop(mob);}return;}if(s.escapeRouteActive){if(!mob.getNavigation().isDone())return;routeFailed(mob);}if(s.escapeDestination!=null){if(s.routeDelay>0)return;if(requestPath(mob,level,s.escapeDestination)){s.escapeRouteActive=true;return;}return;}}if(s.routeBackoff>0)return;if(s.escapeAbandon){s.escapeAbandon=false;s.phase=DreamrootRules.Phase.ROOTED;s.anchor=mob.blockPosition();mob.dreamrootCounters().rerootEvents++;mob.dreamrootCounters().reanchors++;stop(mob);return;}if(s.routeDelay>0)return;int[] searchVisits={0},searchReads={0};for(BlockPos offset:SAFE_OFFSETS){mob.dreamrootCounters().safeCandidates++;BlockPos candidate=mob.blockPosition().offset(offset);if(safe(mob,level,candidate,searchVisits,searchReads)){s.escapeDestination=candidate;if(requestPath(mob,level,candidate)){s.escapeRouteActive=true;mob.dreamrootCounters().hazardRoutes++;return;}return;}}if(s.routeFailures==0){s.escapeAbandon=true;s.routeBackoff=100;mob.dreamrootCounters().pathBackoffs++;}}
    private static boolean requestPath(DreamrootEntity mob,ServerLevel level,BlockPos destination){TransientState s=mob.dreamrootTransient();if(s.routeDelay>0||s.routeBackoff>0)return false;var quota=LivingRootsRules.quota(level);if(!quota.path()){mob.dreamrootCounters().tokensDeferred++;return false;}s.routeDelay=20;mob.dreamrootCounters().pathRequests++;var path=mob.getNavigation().createPath(destination,0);boolean accepted=path!=null&&path.canReach()&&mob.getNavigation().moveTo(path,1.35);if(accepted){mob.dreamrootCounters().pathsAccepted++;return true;}routeFailed(mob);return false;}
    private static void routeFailed(DreamrootEntity mob){TransientState s=mob.dreamrootTransient();s.escapeRouteActive=false;s.routeFailures++;mob.dreamrootCounters().pathFailures++;if(DreamrootRules.clearEscapeDestination(s.routeFailures)){s.escapeDestination=null;s.escapeAbandon=true;s.routeBackoff=100;mob.dreamrootCounters().pathBackoffs++;}}
    private static boolean safe(DreamrootEntity mob,ServerLevel level,BlockPos pos,int[] searchVisits,int[] searchReads){AABB box=mob.getBoundingBox().move(pos.getX()+.5-mob.getX(),pos.getY()-mob.getY(),pos.getZ()+.5-mob.getZ());var quota=LivingRootsRules.quota(level);int remaining=DreamrootRules.SAFE_READ_CAP-searchReads[0];if(remaining<=0)return false;var observation=LivingRootsRules.observeSafeDestination(level,mob,pos,remaining,DreamrootRuntime::unsafe);if(!quota.reads(observation.actualReads()))return false;searchReads[0]+=observation.actualReads();mob.dreamrootCounters().safeReads+=observation.actualReads();if(!observation.safe())return false;var occupants=new ArrayList<net.minecraft.world.entity.Entity>();int cap=Math.min(DreamrootRules.OCCUPANCY_VISITS_PER_CANDIDATE,DreamrootRules.OCCUPANCY_VISITS_PER_SEARCH-searchVisits[0]);if(cap<=0)return false;level.getEntities(EntityTypeTest.forClass(net.minecraft.world.entity.Entity.class),box,e->true,occupants,cap);if(!quota.occupancy(occupants.size()))return false;searchVisits[0]+=occupants.size();mob.dreamrootCounters().safeEntityVisits+=occupants.size();return occupants.stream().noneMatch(e->e!=mob&&e.isAlive()&&e.canBeCollidedWith(mob));}
    private static boolean unsafe(net.minecraft.world.level.block.state.BlockState state){return state.is(Blocks.FIRE)||state.is(Blocks.SOUL_FIRE)||state.is(Blocks.CAMPFIRE)||state.is(Blocks.SOUL_CAMPFIRE)||state.is(Blocks.MAGMA_BLOCK)||state.is(Blocks.CACTUS)||state.is(Blocks.SWEET_BERRY_BUSH);}
    private static boolean livingGround(DreamrootEntity mob){return mob.level().getBlockState(mob.blockPosition().below()).is(CreatureBehaviorTags.Blocks.LIVING_GROUND);}
    private static LivingEntity subject(ServerLevel level,UUID id,ResourceKey<Level> dimension){if(dimension!=null&&dimension!=level.dimension())return null;var e=id==null?null:level.getEntity(id);return e instanceof LivingEntity living&&living.isAlive()?living:null;}
    private static CancellationReason actorCancellationReason(LivingEntity actor){
        if(actor instanceof Player player&&player.isSleeping())return CancellationReason.SLEEP;
        if(actor instanceof net.minecraft.world.entity.npc.villager.AbstractVillager villager&&villager.getTradingPlayer()!=null)return CancellationReason.TRADE;
        if(actor instanceof net.minecraft.world.entity.animal.Animal animal&&animal.isInLove())return CancellationReason.BREEDING;
        if(actor instanceof net.minecraft.world.entity.npc.villager.Villager villager){
            if(villager.getBrain().hasMemoryValue(net.minecraft.world.entity.ai.memory.MemoryModuleType.BREED_TARGET))return CancellationReason.BREEDING;
            if(villager.getBrain().hasMemoryValue(net.minecraft.world.entity.ai.memory.MemoryModuleType.IS_PANICKING)
                ||villager.getBrain().isActive(net.minecraft.world.entity.schedule.Activity.PANIC))return CancellationReason.PANIC;
        }
        if(actor instanceof net.minecraft.world.entity.raid.Raider raider&&raider.getCurrentRaid()!=null)return CancellationReason.RAID;
        return null;
    }
    private static void feedback(DreamrootEntity mob,ServerLevel level){Counters c=mob.dreamrootCounters();if(!LivingRootsRules.quota(level).feedback()){c.feedbackSuppressed++;return;}level.playSound(null,mob.blockPosition(),SoundEvents.GRASS_STEP,SoundSource.HOSTILE,.8F,1.2F);level.sendParticles(ParticleTypes.PORTAL,mob.getX(),mob.getEyeY(),mob.getZ(),8,.4,.4,.4,0);c.feedbackEmitted++;c.sounds++;c.particles+=8;}
    private static void cancelEpisode(DreamrootEntity mob,CancellationReason reason){TransientState s=mob.dreamrootTransient();s.subject=s.attacker=null;s.subjectDimension=s.attackerDimension=null;s.escapeDestination=null;s.escapeAbandon=s.escapeRouteActive=false;s.phaseTicks=s.combatTicks=s.meleeDelay=s.unseenTicks=s.routeDelay=s.routeFailures=s.routeBackoff=0;s.anchor=null;mob.dreamrootCounters().episodeCancelsByReason++;mob.dreamrootCounters().cancellations++;stop(mob);}
    public static void cancel(DreamrootEntity mob){cancelEpisode(mob,CancellationReason.REMOVAL);mob.dreamrootTransient().resetForLoad();}
    private static void stop(DreamrootEntity mob){mob.getNavigation().stop();mob.getMoveControl().setWait();var v=mob.getDeltaMovement();mob.setDeltaMovement(0,v.y,0);mob.setTarget(null);}
}
